Repository opensearch-project/dashboards-query-workbench, pull requests merged in 2023-04, with the labels that each got.

#57 Add 2.7 release notes
  release-notes/opensearch-query-workbench.release-notes-2.7.0.0.md
Labels: release

#60 Add fix for CVE-2023-2251
  package.json
  yarn.lock
Labels: backport 2.x, backport 1.3

#62 [Backport 2.x] Add fix for CVE-2023-2251
  package.json
  yarn.lock
Labels: dependencies, backport 2.7
