Repository opensearch-project/dashboards-query-workbench, pull requests merged in 2024-09, with the labels that each got.

#382 [Bug]fix for missing id in old nav
  public/components/Main/main.tsx
  public/components/acceleration/selectors/source_selector.tsx
Labels: bug, backport 2.x, backport 2.17

#388 Add release notes for 2.17.0
  release-notes/opensearch-query-workbench.release-notes-2.17.0.0.md
Labels: backport 2.x, Maintenance, v2.17.0, backport 2.17

#396 [CVE] Bump the lint-staged from 13.1.0 to 15.2.10
  package.json
  release-notes/opensearch-query-workbench.release-notes-2.17.0.0.md
  yarn.lock
Labels: backport 2.x, Maintenance, backport 2.17
