Repository opensearch-project/dashboards-query-workbench, pull requests merged in 2025-02, with the labels that each got.

#437 Add release notes for 2.19.0
  release-notes/opensearch-query-workbench.release-notes-2.19.0.0.md
Labels: backport 2.x, backport 2.19

#441 Update yarn.lock for cross-spawn
  release-notes/opensearch-query-workbench.release-notes-2.19.0.0.md
  yarn.lock
Labels: backport 2.x, backport 2.19

#448 [Bug]Side tree flyout fix in async operations
  public/components/SQLPage/sql_catalog_tree/s3_tree.tsx
  public/components/SQLPage/sql_catalog_tree/s3_tree_helpers.tsx
  public/dependencies/register_observability_dependencies.tsx
Labels: bug, backport 2.x

#444 Bump dashboards query workbench to version 3.0.0.0-alpha1
  .github/workflows/cypress-e2e-sql-workbench-test.yml
  .github/workflows/ftr-e2e-sql-workbench-test.yml
  .github/workflows/verify-binary-installation.yml
  opensearch_dashboards.json
  package.json
Labels: release, v3.0.0

#453 update CIs to install job-scheduler plugin
  .github/workflows/cypress-e2e-sql-workbench-test.yml
  .github/workflows/ftr-e2e-sql-workbench-test.yml
Labels: Maintenance
