Repository opensearch-project/dashboards-query-workbench, pull requests merged in 2025-01, with the labels that each got.

#430 Downgrade cypress to 12.17.4
  .github/workflows/cypress-e2e-sql-workbench-test.yml
  .github/workflows/ftr-e2e-sql-workbench-test.yml
  .github/workflows/sql-workbench-test-build-workflow.yml
  package.json
  yarn.lock
Labels: backport 2.x, Maintenance, v2.19.0

#433 [Backport 2.x]Downgrade cypress to 12.17.4 (#430)
  .github/workflows/cypress-e2e-sql-workbench-test.yml
  .github/workflows/ftr-e2e-sql-workbench-test.yml
  .github/workflows/sql-workbench-test-build-workflow.yml
  package.json
  yarn.lock
Labels: v2.19.0

#434 [CVE-2024-21538] Bump cross-spawn from 6.0.5 and 7.0.3 to 7.0.5
  package.json
  yarn.lock
Labels: backport 2.x, Maintenance, backport 2.19
